//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Site {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Site() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Site", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 上级类别不得与自身相同! 的本地化字符串。
        /// </summary>
        internal static string BaseDifferent {
            get {
                return ResourceManager.GetString("BaseDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加权限 &gt;&gt; 的本地化字符串。
        /// </summary>
        internal static string btnAddPermissionText {
            get {
                return ResourceManager.GetString("btnAddPermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加 的本地化字符串。
        /// </summary>
        internal static string btnAddText {
            get {
                return ResourceManager.GetString("btnAddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新调整 的本地化字符串。
        /// </summary>
        internal static string btnAdjustText {
            get {
                return ResourceManager.GetString("btnAdjustText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量审核 的本地化字符串。
        /// </summary>
        internal static string btnApproveListText {
            get {
                return ResourceManager.GetString("btnApproveListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核 的本地化字符串。
        /// </summary>
        internal static string btnApproveText {
            get {
                return ResourceManager.GetString("btnApproveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 考核 的本地化字符串。
        /// </summary>
        internal static string btnAssessmentText {
            get {
                return ResourceManager.GetString("btnAssessmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配 的本地化字符串。
        /// </summary>
        internal static string btnAssignmentText {
            get {
                return ResourceManager.GetString("btnAssignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string btnBackText {
            get {
                return ResourceManager.GetString("btnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算 的本地化字符串。
        /// </summary>
        internal static string btnCalculateText {
            get {
                return ResourceManager.GetString("btnCalculateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string btnCancleText {
            get {
                return ResourceManager.GetString("btnCancleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量关闭 的本地化字符串。
        /// </summary>
        internal static string btnCloseListText {
            get {
                return ResourceManager.GetString("btnCloseListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成文件 的本地化字符串。
        /// </summary>
        internal static string btnCreateFile {
            get {
                return ResourceManager.GetString("btnCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量删除 的本地化字符串。
        /// </summary>
        internal static string btnDeleteListText {
            get {
                return ResourceManager.GetString("btnDeleteListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string btnDeleteText {
            get {
                return ResourceManager.GetString("btnDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详细 的本地化字符串。
        /// </summary>
        internal static string btnDetailText {
            get {
                return ResourceManager.GetString("btnDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向下 的本地化字符串。
        /// </summary>
        internal static string btnDownText {
            get {
                return ResourceManager.GetString("btnDownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string btnEditText {
            get {
                return ResourceManager.GetString("btnEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string btnModifyText {
            get {
                return ResourceManager.GetString("btnModifyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动到 的本地化字符串。
        /// </summary>
        internal static string btnMoveToText {
            get {
                return ResourceManager.GetString("btnMoveToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        internal static string btnNextText {
            get {
                return ResourceManager.GetString("btnNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string btnOKText {
            get {
                return ResourceManager.GetString("btnOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量打开 的本地化字符串。
        /// </summary>
        internal static string btnOpenListText {
            get {
                return ResourceManager.GetString("btnOpenListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发放 的本地化字符串。
        /// </summary>
        internal static string btnPayText {
            get {
                return ResourceManager.GetString("btnPayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string btnQueryText {
            get {
                return ResourceManager.GetString("btnQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;&lt; 移除权限 的本地化字符串。
        /// </summary>
        internal static string btnRemovePermissionText {
            get {
                return ResourceManager.GetString("btnRemovePermissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string btnSaveText {
            get {
                return ResourceManager.GetString("btnSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string btnSearchText {
            get {
                return ResourceManager.GetString("btnSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为无效 的本地化字符串。
        /// </summary>
        internal static string btnSetInvalidText {
            get {
                return ResourceManager.GetString("btnSetInvalidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为有效 的本地化字符串。
        /// </summary>
        internal static string btnSetValidText {
            get {
                return ResourceManager.GetString("btnSetValidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        internal static string btnShowText {
            get {
                return ResourceManager.GetString("btnShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量结束进程 的本地化字符串。
        /// </summary>
        internal static string btnStopRouteListText {
            get {
                return ResourceManager.GetString("btnStopRouteListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        internal static string btnUpdateText {
            get {
                return ResourceManager.GetString("btnUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向上 的本地化字符串。
        /// </summary>
        internal static string btnUpText {
            get {
                return ResourceManager.GetString("btnUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库执行错误。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL {
            get {
                return ResourceManager.GetString("ErrorMessageSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeadLock Victim 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL1205 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQLServer不存在或访问被拒绝。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL17 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL18456 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL18456", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unique Index/Constriant Violation. 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL2601 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL2601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库中已经存在相同的数据。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL2627 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL2627", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的数据库。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL4060 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL4060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已经被其它地方引用，无法执行该操作。 的本地化字符串。
        /// </summary>
        internal static string ErrorMessageSQL547 {
            get {
                return ResourceManager.GetString("ErrorMessageSQL547", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统提示： 的本地化字符串。
        /// </summary>
        internal static string ErrorSystemTip {
            get {
                return ResourceManager.GetString("ErrorSystemTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码确认 的本地化字符串。
        /// </summary>
        internal static string fieldConfirmationPassword {
            get {
                return ResourceManager.GetString("fieldConfirmationPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string fieldEmail {
            get {
                return ResourceManager.GetString("fieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原密码 的本地化字符串。
        /// </summary>
        internal static string fieldOldPassword {
            get {
                return ResourceManager.GetString("fieldOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string fieldPassword {
            get {
                return ResourceManager.GetString("fieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        internal static string fieldSex {
            get {
                return ResourceManager.GetString("fieldSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        internal static string fieldSexF {
            get {
                return ResourceManager.GetString("fieldSexF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        internal static string fieldSexM {
            get {
                return ResourceManager.GetString("fieldSexM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string fieldTelphone {
            get {
                return ResourceManager.GetString("fieldTelphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真实姓名 的本地化字符串。
        /// </summary>
        internal static string fieldTrueName {
            get {
                return ResourceManager.GetString("fieldTrueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string fieldUserName {
            get {
                return ResourceManager.GetString("fieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        internal static string fieldUserType {
            get {
                return ResourceManager.GetString("fieldUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Excel 的本地化字符串。
        /// </summary>
        internal static string GVTextExportExcel {
            get {
                return ResourceManager.GetString("GVTextExportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Word 的本地化字符串。
        /// </summary>
        internal static string GVTextExportWord {
            get {
                return ResourceManager.GetString("GVTextExportWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第一页 的本地化字符串。
        /// </summary>
        internal static string GVTextFirst {
            get {
                return ResourceManager.GetString("GVTextFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一页 的本地化字符串。
        /// </summary>
        internal static string GVTextLast {
            get {
                return ResourceManager.GetString("GVTextLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        internal static string GVTextNext {
            get {
                return ResourceManager.GetString("GVTextNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        internal static string GVTextPage {
            get {
                return ResourceManager.GetString("GVTextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        internal static string GVTextPrevious {
            get {
                return ResourceManager.GetString("GVTextPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录 的本地化字符串。
        /// </summary>
        internal static string GVTextRecord {
            get {
                return ResourceManager.GetString("GVTextRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加角色 的本地化字符串。
        /// </summary>
        internal static string lblAddRole {
            get {
                return ResourceManager.GetString("lblAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        internal static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string lblFalse {
            get {
                return ResourceManager.GetString("lblFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键字 的本地化字符串。
        /// </summary>
        internal static string lblKeyword {
            get {
                return ResourceManager.GetString("lblKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新角色名 的本地化字符串。
        /// </summary>
        internal static string lblNewRoleName {
            get {
                return ResourceManager.GetString("lblNewRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string lblOperation {
            get {
                return ResourceManager.GetString("lblOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string lblRole {
            get {
                return ResourceManager.GetString("lblRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string lblSearch {
            get {
                return ResourceManager.GetString("lblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string lblTrue {
            get {
                return ResourceManager.GetString("lblTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能行为管理 的本地化字符串。
        /// </summary>
        internal static string ptActions {
            get {
                return ResourceManager.GetString("ptActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加用户 的本地化字符串。
        /// </summary>
        internal static string ptAddUser {
            get {
                return ResourceManager.GetString("ptAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编辑 的本地化字符串。
        /// </summary>
        internal static string ptEditRole {
            get {
                return ResourceManager.GetString("ptEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        internal static string ptPermissionAdmin {
            get {
                return ResourceManager.GetString("ptPermissionAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string ptRoleAdmin {
            get {
                return ResourceManager.GetString("ptRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色分配 的本地化字符串。
        /// </summary>
        internal static string ptRoleAssignment {
            get {
                return ResourceManager.GetString("ptRoleAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string ptUserAdmin {
            get {
                return ResourceManager.GetString("ptUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        internal static string ptUserInfo {
            get {
                return ResourceManager.GetString("ptUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户更新 的本地化字符串。
        /// </summary>
        internal static string ptUserUpdate {
            get {
                return ResourceManager.GetString("ptUserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该编码已经存在，请更换其他编码。 的本地化字符串。
        /// </summary>
        internal static string TooltipCodeExist {
            get {
                return ResourceManager.GetString("TooltipCodeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据已经被其它数据使用，不能再进行修改！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDataBeUsed {
            get {
                return ResourceManager.GetString("TooltipDataBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该信息已经存在！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDataExist {
            get {
                return ResourceManager.GetString("TooltipDataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确认要删除吗？ 的本地化字符串。
        /// </summary>
        internal static string TooltipDelConfirm {
            get {
                return ResourceManager.GetString("TooltipDelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipDelOK {
            get {
                return ResourceManager.GetString("TooltipDelOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你的帐号已在别处登陆，你被强迫下线！ 的本地化字符串。
        /// </summary>
        internal static string TooltipForceLogin {
            get {
                return ResourceManager.GetString("TooltipForceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string TooltipFormatErr {
            get {
                return ResourceManager.GetString("TooltipFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入数据不正确！ 的本地化字符串。
        /// </summary>
        internal static string TooltipInputDataErr {
            get {
                return ResourceManager.GetString("TooltipInputDataErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你尚未登录或无权访问，请重新登录！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoAuthenticated {
            get {
                return ResourceManager.GetString("TooltipNoAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入内容！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoNull {
            get {
                return ResourceManager.GetString("TooltipNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你没有权限访问该页！请重新登录或联系管理员！ 的本地化字符串。
        /// </summary>
        internal static string TooltipNoPermission {
            get {
                return ResourceManager.GetString("TooltipNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是数字格式 的本地化字符串。
        /// </summary>
        internal static string TooltipNumFormatErr {
            get {
                return ResourceManager.GetString("TooltipNumFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSaveError {
            get {
                return ResourceManager.GetString("TooltipSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSaveOK {
            get {
                return ResourceManager.GetString("TooltipSaveOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你登录超时，请重新登录！ 的本地化字符串。
        /// </summary>
        internal static string TooltipSessionExpired {
            get {
                return ResourceManager.GetString("TooltipSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是日期格式 的本地化字符串。
        /// </summary>
        internal static string TooltipTimeFormatErr {
            get {
                return ResourceManager.GetString("TooltipTimeFormatErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateError {
            get {
                return ResourceManager.GetString("TooltipUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUpdateOK {
            get {
                return ResourceManager.GetString("TooltipUpdateOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经存在！ 的本地化字符串。
        /// </summary>
        internal static string TooltipUserExist {
            get {
                return ResourceManager.GetString("TooltipUserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货币单位 的本地化字符串。
        /// </summary>
        internal static string UnitCurrency {
            get {
                return ResourceManager.GetString("UnitCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计量单位 的本地化字符串。
        /// </summary>
        internal static string UnitMeasure {
            get {
                return ResourceManager.GetString("UnitMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无单位 的本地化字符串。
        /// </summary>
        internal static string UnitNone {
            get {
                return ResourceManager.GetString("UnitNone", resourceCulture);
            }
        }
    }
}
