//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysManage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysManage() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysManage", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 设置功能权限 的本地化字符串。
        /// </summary>
        internal static string btnSetupPerm {
            get {
                return ResourceManager.GetString("btnSetupPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string fieldcomment {
            get {
                return ResourceManager.GetString("fieldcomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        internal static string fieldDescription {
            get {
                return ResourceManager.GetString("fieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cField {
            get {
                return ResourceManager.GetString("fieldMultiLang_cField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cLang {
            get {
                return ResourceManager.GetString("fieldMultiLang_cLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段值 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_cValue {
            get {
                return ResourceManager.GetString("fieldMultiLang_cValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外键值 的本地化字符串。
        /// </summary>
        internal static string fieldMultiLang_iPKValue {
            get {
                return ResourceManager.GetString("fieldMultiLang_iPKValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单ID 的本地化字符串。
        /// </summary>
        internal static string fieldNodeID {
            get {
                return ResourceManager.GetString("fieldNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单名称 的本地化字符串。
        /// </summary>
        internal static string fieldNodeName {
            get {
                return ResourceManager.GetString("fieldNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string fieldOrder {
            get {
                return ResourceManager.GetString("fieldOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顺序 的本地化字符串。
        /// </summary>
        internal static string fieldOrderID {
            get {
                return ResourceManager.GetString("fieldOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父菜单 的本地化字符串。
        /// </summary>
        internal static string fieldParent {
            get {
                return ResourceManager.GetString("fieldParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        internal static string fieldPermission {
            get {
                return ResourceManager.GetString("fieldPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        internal static string fieldText {
            get {
                return ResourceManager.GetString("fieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string fieldUrl {
            get {
                return ResourceManager.GetString("fieldUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 增加多语言数据 的本地化字符串。
        /// </summary>
        internal static string lblAddMultiLang {
            get {
                return ResourceManager.GetString("lblAddMultiLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误日志 的本地化字符串。
        /// </summary>
        internal static string ptErrorlog {
            get {
                return ResourceManager.GetString("ptErrorlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单增加 的本地化字符串。
        /// </summary>
        internal static string ptMenuAdd {
            get {
                return ResourceManager.GetString("ptMenuAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单管理 的本地化字符串。
        /// </summary>
        internal static string ptMenuManage {
            get {
                return ResourceManager.GetString("ptMenuManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单编辑 的本地化字符串。
        /// </summary>
        internal static string ptMenuModify {
            get {
                return ResourceManager.GetString("ptMenuModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单信息 的本地化字符串。
        /// </summary>
        internal static string ptMenuShow {
            get {
                return ResourceManager.GetString("ptMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多语言管理 的本地化字符串。
        /// </summary>
        internal static string ptMultiLanguage {
            get {
                return ResourceManager.GetString("ptMultiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 菜单定制 的本地化字符串。
        /// </summary>
        internal static string ptTreeFavorite {
            get {
                return ResourceManager.GetString("ptTreeFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户日志 的本地化字符串。
        /// </summary>
        internal static string ptUserLog {
            get {
                return ResourceManager.GetString("ptUserLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连续添加 的本地化字符串。
        /// </summary>
        internal static string TooltipAddContinue {
            get {
                return ResourceManager.GetString("TooltipAddContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建同名的权限 的本地化字符串。
        /// </summary>
        internal static string TooltipCreatSamePerm {
            get {
                return ResourceManager.GetString("TooltipCreatSamePerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请为用户选择角色 的本地化字符串。
        /// </summary>
        internal static string TooltipRoleAssignForuser {
            get {
                return ResourceManager.GetString("TooltipRoleAssignForuser", resourceCulture);
            }
        }
    }
}
