//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TaoCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaoCategories() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TaoCategories", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分类介绍最多只能输入1000个字符 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_CategoryDesc_ErrorFormat {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_CategoryDesc_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称不能为空，长度限制在30个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_CategoryName_ErrorFormat {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_CategoryName_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择此分类的上级分类 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_ParentCategory {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_ParentCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告诉搜索引擎此分类浏览页面的主要内容，有助于搜索引擎更好的收录此分类浏览页面 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_MetaDesc_Help {
            get {
                return ResourceManager.GetString("IDS_FormField_MetaDesc_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置分类的关键字，让用户可以通过搜索引擎搜索到此分类的浏览页面 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_MetaKeywords_Help {
            get {
                return ResourceManager.GetString("IDS_FormField_MetaKeywords_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品类型是一系列属性集合，在这里选择商品类型将会被套用到此商品分类。 的本地化字符串。
        /// </summary>
        internal static string IDS_Label_ProductType {
            get {
                return ResourceManager.GetString("IDS_Label_ProductType", resourceCulture);
            }
        }
    }
}
