//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class topcategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal topcategories() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.topcategories", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称不能为空，长度限制在100个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_CategoryName_ErrorFormat {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_CategoryName_ErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择您要删除的顶级分类 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_CheckSelected {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_CheckSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置商品分类的显示顺序 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_DisplaySequence {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_DisplaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL重写名称只能包含英文字母、下划线和减号 的本地化字符串。
        /// </summary>
        internal static string IDS_ErrorMessage_RewriteNameFormat {
            get {
                return ResourceManager.GetString("IDS_ErrorMessage_RewriteNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导购信息 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_Buy {
            get {
                return ResourceManager.GetString("IDS_FormField_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示顺序 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_CategoryDisplaySequence {
            get {
                return ResourceManager.GetString("IDS_FormField_CategoryDisplaySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类图片 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_CategoryIcon {
            get {
                return ResourceManager.GetString("IDS_FormField_CategoryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_CategoryName {
            get {
                return ResourceManager.GetString("IDS_FormField_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告诉搜索引擎此分类浏览页面的主要内容，有助于搜索引擎更好的收录此分类浏览页面 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_MetaDesc_Help {
            get {
                return ResourceManager.GetString("IDS_FormField_MetaDesc_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置分类的关键字，让用户可以通过搜索引擎搜索到此分类的浏览页面 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_MetaKeywords_Help {
            get {
                return ResourceManager.GetString("IDS_FormField_MetaKeywords_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类描述 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_PageDesc {
            get {
                return ResourceManager.GetString("IDS_FormField_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键字 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_PagekeyWords {
            get {
                return ResourceManager.GetString("IDS_FormField_PagekeyWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品模板 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_ProductTemplet {
            get {
                return ResourceManager.GetString("IDS_FormField_ProductTemplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为此顶级分类指定一个商品模板，此分类下的所有商品将自动附加所选商品模板的扩展属性和配件 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_ProductTempletHelp {
            get {
                return ResourceManager.GetString("IDS_FormField_ProductTempletHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL重写名称 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_RewriteName {
            get {
                return ResourceManager.GetString("IDS_FormField_RewriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用URL重写可以增加分类浏览页面对搜索引擎的友好性，您需要为每一个顶级分类指定一个重写名称，比如服装可以填写clothing，手机可以填写mobile，长度限制在50个字符以内 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_RewriteNameHelp {
            get {
                return ResourceManager.GetString("IDS_FormField_RewriteNameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加扩展属性 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_ViewAttribute {
            get {
                return ResourceManager.GetString("IDS_FormField_ViewAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加实物配件 的本地化字符串。
        /// </summary>
        internal static string IDS_FormField_ViewCustomerLookupList {
            get {
                return ResourceManager.GetString("IDS_FormField_ViewCustomerLookupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加顶级分类 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_litAddTopCategory {
            get {
                return ResourceManager.GetString("IDS_FromField_litAddTopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑顶级分类 的本地化字符串。
        /// </summary>
        internal static string IDS_FromField_litUpdateTopCategory {
            get {
                return ResourceManager.GetString("IDS_FromField_litUpdateTopCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类编号 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_Id {
            get {
                return ResourceManager.GetString("IDS_Header_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_Name {
            get {
                return ResourceManager.GetString("IDS_Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品模板 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_ProductTemplet {
            get {
                return ResourceManager.GetString("IDS_Header_ProductTemplet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL重写名称 的本地化字符串。
        /// </summary>
        internal static string IDS_Header_RewriteName {
            get {
                return ResourceManager.GetString("IDS_Header_RewriteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理网站的商品分类.您可以添加、编辑、删除商品分类 的本地化字符串。
        /// </summary>
        internal static string IDS_PageDesc {
            get {
                return ResourceManager.GetString("IDS_PageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品分类管理 的本地化字符串。
        /// </summary>
        internal static string IDS_PageTitle {
            get {
                return ResourceManager.GetString("IDS_PageTitle", resourceCulture);
            }
        }
    }
}
